# Generated by Django 5.1.1 on 2024-09-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdf_file',
            new_name='book',
        ),
    ]
