# Generated by Django 5.1.1 on 2024-09-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_rename_pdf_file_book_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
