# Generated by Django 5.1.1 on 2024-09-06 20:43

import book_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0003_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(blank=True, null=True, upload_to=book_api.models.book_upload_path),
        ),
    ]
