# Generated by Django 5.1.1 on 2024-09-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0006_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='topics',
            field=models.ManyToManyField(related_name='books', to='book_api.topic'),
        ),
    ]
