# Generated by Django 5.1.1 on 2024-09-07 12:35

import book_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0007_book_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_code',
            field=models.BigIntegerField(default=book_api.models.generate_book_code, editable=False, unique=True),
        ),
    ]
