# Generated by Django 5.1.1 on 2024-09-07 13:52

import book_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0008_book_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=book_api.models.book_upload_path),
        ),
    ]
