# Generated by Django 5.1.1 on 2024-09-11 06:52

import BookShelf.utilities.storage
import book_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0009_alter_book_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(blank=True, max_length=255, null=True, storage=BookShelf.utilities.storage.ReplaceExistingFileStorage(), upload_to=book_api.models.book_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='book_api.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='books', to='book_api.topic'),
        ),
    ]
