# Generated by Django 5.1.1 on 2024-09-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0014_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
