# Generated by Django 5.1.1 on 2024-09-19 14:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0017_genre_unique_genre_name_case_insensitive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genre',
            name='unique_genre_name_case_insensitive',
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='Unique Genre name is not case sensitive.'),
        ),
    ]
