# Generated by Django 5.1.1 on 2024-09-21 14:12

import BookShelf.utilities.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0020_topic_added_by_topic_added_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[BookShelf.utilities.validator.validate_no_spaces]),
        ),
    ]
