# Generated by Django 5.1.1 on 2024-09-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_api', '0004_author_middle_name_alter_author_first_name_and_more'),
        ('book_api', '0021_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='author_api.author'),
        ),
    ]
