# Generated by Django 5.1.1 on 2024-10-31 14:00

import BookShelf.utilities.storage
import user_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_user_middle_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=BookShelf.utilities.storage.ReplaceExistingFileStorage(), upload_to=user_api.models.profile_upload_path),
        ),
    ]
