# Generated by Django 5.1.1 on 2024-10-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_user_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cover_image',
            new_name='profile_image',
        ),
    ]
