# Generated by Django 5.1.1 on 2024-12-02 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
