# Generated by Django 5.1.1 on 2024-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0003_activitylog_activity_time_alter_activitylog_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Activity Time'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='query_params',
            field=models.TextField(blank=True, null=True, verbose_name='Query Params'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.JSONField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
