# Generated by Django 5.1.1 on 2024-12-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0004_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
