# Generated by Django 5.1.1 on 2024-12-13 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0005_alter_activitylog_user_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('object', models.CharField(choices=[('book', 'Book'), ('author', 'Author'), ('publisher', 'Publisher'), ('genre', 'Genre'), ('topic', 'Topic')], max_length=10)),
                ('event', models.CharField(choices=[('retrieve', 'Retrieve'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('data', models.JSONField(blank=True, null=True)),
                ('added_date_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_api.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
            },
        ),
    ]
